
modLoader="javafml" #mandatory
loaderVersion="[40,)"
license="MIT"
[[mods]] 
modId="timelessarsenal"
version="${file.jarVersion}"
displayName="Timeless Arsenal"
authors="bfybf"
description='''
'''

[[dependencies.timelessarsenal]]
    modId="forge" 
    mandatory=true 
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.timelessarsenal]]
    modId="create"
    mandatory=true
    versionRange="[mc1.18.2_v0.5.1b,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.timelessarsenal]]
    modId="tac"
    mandatory=true
    versionRange="[0.3.10-1.18.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.timelessarsenal]]
    modId="alloyed"
    mandatory=false
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"